### ISSUE TITLE
ESP8266 or Arduino compatibility?

### ISSUE THREAD

**Issue by japamar** [sivann/crowalarm#1]
Hi Sivann,

Thanks for your great job with this Crow alarm.
Is it possible you can make this code usable for ESP8266 or Arduino platform?
I which I could program in Pyton or C++ but i don't have the knowledge :(
It would be amazing if you could do that and I'm sure many other people would apreciate.
Thank you once again!
Jaime

**Comment by sivann** [comment]
Hi Jaime I have no idea about esp8266. Good luck with your project.

**Comment by MadDoct** [comment]
> Hi Sivann,
> 
> Thanks for your great job with this Crow alarm. Is it possible you can make this code usable for ESP8266 or Arduino platform? I which I could program in Pyton or C++ but i don't have the knowledge :( It would be amazing if you could do that and I'm sure many other people would apreciate. Thank you once again! Jaime

Jaime, I made what you wanted:
https://github.com/MadDoct/ESP-CrowAlarmInterface

Sivann, thanks for finding out how to get the raw data from the alarm. I used that info for my project...

**Comment by japamar** [comment]
Great news MadDoct!!
Thank you very much. I will test your code.
Excelente trabalho, muito obrigado!
Depois dou feedback sobre a integração com o homeassistant.
Um grande abraço.
Jaime

**Comment by sivann** [comment]
Hi all, I'm glad you found this usefull, I did not go further with this and did not have more time than 3-4 hours to play with this project. Maybe someday..

**Comment by MadDoct** [comment]
> Great news MadDoct!! Thank you very much. I will test your code. Excelente trabalho, muito obrigado! Depois dou feedback sobre a integração com o homeassistant. Um grande abraço. Jaime

A integração com o HA funciona muito bem... a config já está no repositório.

Sorry for hijacking this, sivann.
