### ISSUE TITLE
Read the alarm status

### ISSUE THREAD

**Issue by MadDoct** [sivann/crowalarm#2]
Hi, is it possible to read the alarm status (armed; armed_home or triggered) using a similar method?
Is there a place where I can read about the protocol? How did you find iut how this worked?

Thanks

**Comment by sivann** [comment]
sorry no place to read the protocol, I reverse engineered with a (salae) logic analyzer.

**Comment by MadDoct** [comment]
Thanks. I closed the issue because in the meantime I was able to reverse engineer those features myself.
